Fix issue

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -27,11 +27,13 @@ jobs:
           echo "Threshold                     : $TEST_COVERAGE_THRESHOLD %"
           totalCoverage=20
           echo "Current test coverage: $totalCoverage %"
-          if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD | awk `{print($1 > $2)`) )); then echo "OK"
-          else
-            echo "Current test coverage is below threshold. Please add more unit tests or adjust thresold to a lower value."
-            exit1
-          fi
+          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                echo "OK"
+            else
+                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                echo "Failed"
+                exit 1
+            fi
 
 #  coverage-test-2:
 #    name: Coverage Diff
